/* Shared SEO configuration for the static site and build-time checks. */
(function (root, factory) {
    if (typeof module === 'object' && module.exports) module.exports = factory();
    else root.WriteUrduSeoConfig = factory();
}(typeof self !== 'undefined' ? self : this, function () {
    var SITE_ORIGIN = 'https://write-urdu.com';
    var PUBLISHER = {
        type: 'Organization',
        name: 'Write Urdu',
        publicMaintainerName: null,
        contactEmail: 'admin@write-urdu.com',
        aboutPath: '/why-write-urdu'
    };
    var pages = [
        { id: 'home', path: '/', legacyPaths: ['/index.html'], indexable: true, title: 'Write Urdu Online – Roman Urdu to Urdu Typing', description: 'Type Roman Urdu with English letters and convert it into Urdu script. Copy, format, share, print, or export Urdu from your browser.', h1: 'Write Urdu online', section: 'tools', priority: 1, changefreq: 'weekly', lastmod: '2026-07-15', schema: ['WebApplication'] },
        { id: 'urdu-editor', path: '/urdu-editor', legacyPaths: ['/urdu-editor.html'], indexable: true, title: 'Urdu Rich Text Editor Online – Format and Export Urdu', description: 'Write and format Urdu with fonts, headings, colours, lists and alignment, then export your document as Word, PDF, PNG or print.', h1: 'Urdu Rich Text Editor', section: 'tools', priority: .95, changefreq: 'monthly', lastmod: '2026-07-15', schema: ['WebApplication'] },
        { id: 'urdu-keyboard', path: '/urdu-keyboard', legacyPaths: ['/urdu-keyboard.html'], indexable: true, title: 'Online Urdu Keyboard – Type Urdu in Your Browser', description: 'Type Urdu directly with an on-screen keyboard or physical keyboard. Copy, save and use Urdu text without installing keyboard software.', h1: 'Urdu Keyboard', section: 'tools', priority: .9, changefreq: 'monthly', lastmod: '2026-07-15', schema: ['WebApplication', 'FAQPage'] },
        { id: 'urdu-card-studio', path: '/urdu-card-studio', legacyPaths: ['/urdu-card-studio.html'], indexable: true, title: 'Urdu Card Maker Online – Create Urdu Quote Images', description: 'Create Urdu quote cards, poetry images and social posts with Urdu fonts, templates and local backgrounds, then download a PNG.', h1: 'Urdu Card Studio', section: 'tools', priority: .9, changefreq: 'monthly', lastmod: '2026-07-15', schema: ['WebApplication', 'FAQPage'] },
        { id: 'urdu-templates', path: '/urdu-templates', legacyPaths: ['/urdu-templates.html'], indexable: true, title: 'Urdu Templates – Quote, Poetry and Social Designs', description: 'Browse free Urdu quote, poetry, social, religious, education, business and event templates, then edit a design directly in Urdu Card Studio.', h1: 'Urdu Template Library', section: 'tools', priority: .88, changefreq: 'monthly', lastmod: '2026-07-16', schema: ['WebApplication', 'CollectionPage', 'ItemList'] },
        { id: 'qr-code-generator', path: '/qr-code-generator', legacyPaths: ['/qr-code-generator.html'], indexable: true, title: 'Free Urdu QR Code Generator – Text, Wi-Fi and WhatsApp', description: 'Create static QR codes for Urdu text, links, Wi-Fi, WhatsApp, contacts and more. Customize colours and logos privately in your browser.', h1: 'Free QR Code Generator', section: 'tools', priority: .9, changefreq: 'monthly', lastmod: '2026-07-15', schema: ['WebApplication', 'FAQPage'] },
        { id: 'urdu-alphabet', path: '/urdu-alphabet', legacyPaths: ['/urdu-alphabet.html'], indexable: true, title: 'Urdu Alphabet Guide – Letters, Names and Writing Direction', description: 'Learn common Urdu letters, their names, right-to-left direction, joining behavior and the Nastaliq writing style.', h1: 'Urdu alphabet', section: 'guides', priority: .8, changefreq: 'yearly', lastmod: '2026-07-15', schema: ['Article'] },
        { id: 'write-urdu-features', path: '/write-urdu-features', legacyPaths: ['/write-urdu-features.html'], indexable: true, title: 'Write Urdu Features – Word, PDF, PNG, Drafts and Sharing', description: 'Learn how to copy, share, recover local drafts, import text, and export Urdu as TXT, Word, PDF, PNG or print.', h1: 'Write Urdu features and export options', section: 'guides', priority: .8, changefreq: 'monthly', lastmod: '2026-07-15', schema: ['Article'] },
        { id: 'urdu-editor-features', path: '/urdu-editor-features', legacyPaths: ['/urdu-editor-features.html'], indexable: true, title: 'Urdu Formatting Guide – Fonts, Colour, Size and Alignment', description: 'Learn how to format Urdu text with fonts, colours, highlights, emphasis, sizes, alignment, undo and redo.', h1: 'Urdu Rich Text Editor formatting guide', section: 'guides', priority: .8, changefreq: 'monthly', lastmod: '2026-07-15', schema: ['Article'] },
        { id: 'write-urdu-documentation', path: '/write-urdu-documentation', legacyPaths: ['/write-urdu-documentation.html'], indexable: true, title: 'How to Use Write Urdu – Complete Editor and Export Guide', description: 'Learn Roman Urdu typing, direct Urdu input, rich formatting, local drafts, exports, Card Studio and QR tools.', h1: 'Write Urdu, beautifully explained.', section: 'guides', priority: .85, changefreq: 'monthly', lastmod: '2026-07-15', schema: ['Article'] },
        { id: 'english-urdu-typing-tutorial', path: '/english-urdu-typing-tutorial', legacyPaths: ['/english-urdu-typing-tutorial.html'], indexable: true, title: 'Roman Urdu to Urdu Typing Tutorial – Step-by-Step Guide', description: 'Follow practical steps and video guides for typing Roman Urdu, choosing suggestions and formatting Urdu documents.', h1: 'Roman Urdu to Urdu typing tutorials', section: 'guides', priority: .75, changefreq: 'yearly', lastmod: '2026-07-15', schema: ['Article'] },
        { id: 'urdu-faq', path: '/urdu-faq', legacyPaths: ['/urdu-faq.html'], indexable: true, title: 'Write Urdu FAQ – Typing, Privacy, Exports and Urdu Script', description: 'Get answers about Roman Urdu transliteration, direct Urdu typing, privacy, local drafts, fonts, exports and the Urdu script.', h1: 'Write Urdu FAQ', section: 'guides', priority: .8, changefreq: 'monthly', lastmod: '2026-07-15', schema: ['FAQPage'] },
        { id: 'why-write-urdu', path: '/why-write-urdu', legacyPaths: ['/why-write-urdu.html'], indexable: true, title: 'About Write Urdu – Purpose, Privacy and How It Works', description: 'Learn why Write Urdu was created, who it helps, how its browser-based tools work and how to report corrections.', h1: 'About Write Urdu', section: 'about', priority: .7, changefreq: 'yearly', lastmod: '2026-07-15', schema: ['Article'] },
        { id: 'write-urdu-privacy', path: '/write-urdu-privacy', legacyPaths: ['/write-urdu-privacy.html'], indexable: true, title: 'Write Urdu Privacy Policy – Local Storage, Cookies and Services', description: 'Understand how Write Urdu handles local drafts, uploaded images, QR content, transliteration, analytics, ads and feedback.', h1: 'Write Urdu privacy policy and terms', section: 'about', priority: .6, changefreq: 'yearly', lastmod: '2026-07-15', schema: ['Article'] },
        { id: 'write-urdu-sitemap', path: '/write-urdu-sitemap', legacyPaths: ['/write-urdu-sitemap.html'], indexable: true, title: 'Write Urdu Sitemap – Editors, Tools, Guides and Policies', description: 'Browse all Write Urdu editors, creative tools, typing guides, documentation, help pages and policies.', h1: 'Write Urdu sitemap', section: 'about', priority: .5, changefreq: 'monthly', lastmod: '2026-07-15', schema: ['WebPage'] },
        { id: 'write-urdu-search', path: '/write-urdu-search', legacyPaths: ['/write-urdu-search.html'], indexable: false, title: 'Search Write Urdu Guides and Tools', description: 'Search Write Urdu documentation, typing guides, export help and information about available browser-based tools.', h1: 'Search Write Urdu', section: 'utility', priority: 0, changefreq: 'yearly', schema: [] },
        { id: 'write-urdu-feedback', path: '/write-urdu-feedback', legacyPaths: ['/write-urdu-feedback.html'], indexable: false, title: 'Write Urdu Feedback and Corrections', description: 'Report an incorrect transliteration, accessibility issue, browser problem or practical feature suggestion.', h1: 'Write Urdu feedback', section: 'utility', priority: 0, changefreq: 'yearly', schema: [] },
        { id: 'roman-urdu-transliteration', path: '/roman-urdu-transliteration', legacyPaths: ['/roman-urdu-transliteration.html'], indexable: true, title: 'Roman Urdu to Urdu Is Transliteration, Not Translation', description: 'Learn how Roman Urdu typing becomes Urdu script, why spellings can be ambiguous, and how to review suggestions in Write Urdu.', h1: 'Roman Urdu to Urdu is transliteration, not translation', section: 'guides', priority: .72, changefreq: 'yearly', lastmod: '2026-07-16', schema: ['Article'] },
        { id: 'urdu-fonts-nastaliq-vs-naskh', path: '/urdu-fonts-nastaliq-vs-naskh', legacyPaths: ['/urdu-fonts-nastaliq-vs-naskh.html'], indexable: true, title: 'Urdu Fonts: Nastaliq vs Naskh – Which Should You Use?', description: 'Compare Nastaliq and Naskh for Urdu documents, quote cards and interface text, with practical guidance for Write Urdu tools.', h1: 'Urdu fonts: Nastaliq versus Naskh', section: 'guides', priority: .72, changefreq: 'yearly', lastmod: '2026-07-16', schema: ['Article'] }
    ];
    var byPath = {};
    pages.forEach(function (page) { byPath[page.path] = page; (page.legacyPaths || []).forEach(function (legacy) { byPath[legacy] = page; }); });
    return { SITE_ORIGIN: SITE_ORIGIN, PUBLISHER: PUBLISHER, pages: pages, byPath: byPath, canonical: function (path) { return SITE_ORIGIN + (path === '/' ? '/' : path); } };
}));
