const assert = require('node:assert');
const fs = require('node:fs');
const path = require('node:path');
const seo = require('../seo.config.js');
const core = require('../js/card-gallery-core.js');
const backgrounds = require('../js/card-background-registry.js').getAllBackgrounds();

const root = path.resolve(__dirname, '..');
const read = relative => fs.readFileSync(path.join(root, relative), 'utf8');
const html = read('urdu-card-gallery.html');
const script = read('js/card-gallery.js');
const css = read('css/card-gallery.css');
const registry = read('docs/WU-PUBLIC-PAGE-REGISTRY.csv');
const sitemap = read('sitemap.xml');
const llms = read('llms.txt');
const discoveryGuide = (html.match(/<section class="card-discovery-guide"[^]*?<\/section>/) || [''])[0];

assert.match(html, /<h1[^>]*>See your Urdu on every card<\/h1>/);
assert.match(html, /name="robots" content="index,follow"/, 'WU-CARD-GALLERY-001 P0.9 founder exception (2026-09-13) made this route indexable');
assert.match(html, /name="googlebot" content="index,follow"/);
assert.match(html, /href="https:\/\/write-urdu\.com\/urdu-card-gallery"/);
assert.match(html, /data-card-gallery-input[^>]+lang="ur"[^>]+dir="rtl"[^>]+maxlength="600"/);
assert.match(html, /data-card-gallery-grid/);
assert.match(html, new RegExp(`data-card-gallery-count[^>]*>${backgrounds.length} designs<`), 'source count must match the shared background registry');
assert.match(html, /<h2[^>]*>Choose a design for your Urdu text<\/h2>/, 'indexed route needs useful source-visible guidance');
['/', '/urdu-cards', '/urdu-card-studio', '/how-to-write-urdu-on-photo'].forEach(route => {
    assert.ok(discoveryGuide.includes(`href="${route}"`), `gallery guidance must link contextually to ${route}`);
});
assert.strictEqual(seo.byPath['/urdu-card-gallery'].indexable, true, 'P0.9 founder exception made this a distinct-intent indexed route');
assert.match(registry, /urdu-card-gallery\.html,\/urdu-card-gallery,Create,[^\n]+,index,yes,/);
assert.match(sitemap, /urdu-card-gallery/);
assert.match(llms, /urdu-card-gallery/);
assert.match(script, /registry\.getAllBackgrounds\(\)\.forEach\(function \(background\) \{\s*createPreview\(background, fragment\);/, 'shared registry must own gallery inventory');
assert.match(script, /requestAnimationFrame\(refreshPreviews\)/, 'input refresh must be frame-batched');
assert.match(script, /record\.text\.textContent = value/, 'typing must update existing DOM text nodes');
assert.doesNotMatch(script, /createElement\(['"]canvas['"]\)|getContext\(/, 'gallery must not create preview canvases');
assert.doesNotMatch(script, /fetch\(/, 'typing runtime must not fetch artwork');
assert.match(script, /image\.loading = 'lazy'/);
assert.match(script, /image\.src = background\.thumbnailSrc \|\| background\.src/);
assert.match(script, /text\.lang = 'ur'/);
assert.match(script, /text\.dir = 'rtl'/);
assert.match(script, /core\.isSuitable\(bucket, record\.background\.textCapacity\)/);
assert.doesNotMatch(css, /text-overflow\s*:\s*ellipsis[^}]*card-gallery-preview-text|card-gallery-preview-text[^}]*text-overflow\s*:\s*ellipsis/i);
assert.match(css, /unicode-bidi:plaintext/);
assert.match(css, /overflow-wrap:anywhere/);
assert.strictEqual(core.previewTextTier(''), 'short');
assert.strictEqual(core.previewTextTier('محبت روشنی ہے'), 'short');
assert.strictEqual(core.previewTextTier('ا'.repeat(100)), 'medium');
assert.strictEqual(core.previewTextTier('ا'.repeat(300)), 'long');

console.log('Card Gallery Slice 1 contract passed: indexed DOM-preview route (P0.9 exception), shared registry, and frame-batched updates.');
