-- WU-PLAT-002H Gate B2 M1: mobile-specific first-value funnel reconciliation.
-- product_hourly_metrics and product_hourly_locale_metrics store writer
-- funnel counters and device_mobile/tablet/desktop counters as independent
-- columns on the same (bucket_hour, tool) row -- not cross-tabbed -- so the
-- mobile-only "writer_first_input / writer_eligible" primary metric required
-- by WU-PLAT-002H-MOBILE-ACTIVATION-REPAIR.md 9.2 cannot be computed from
-- them. This adds a device_class dimension mirroring the existing locale
-- rollup (0008_locale_metrics.sql), scoped the same way: no writing,
-- transcript, filename, or identity content, only bounded aggregate counters.

CREATE TABLE IF NOT EXISTS product_hourly_device_metrics (
    bucket_hour TEXT NOT NULL,
    device_class TEXT NOT NULL,
    tool TEXT NOT NULL,
    visits INTEGER NOT NULL DEFAULT 0,
    engaged_visits INTEGER NOT NULL DEFAULT 0,
    copies INTEGER NOT NULL DEFAULT 0,
    exports INTEGER NOT NULL DEFAULT 0,
    export_pdf INTEGER NOT NULL DEFAULT 0,
    export_png INTEGER NOT NULL DEFAULT 0,
    export_png_transparent INTEGER NOT NULL DEFAULT 0,
    export_jpeg INTEGER NOT NULL DEFAULT 0,
    export_doc INTEGER NOT NULL DEFAULT 0,
    export_txt INTEGER NOT NULL DEFAULT 0,
    export_svg INTEGER NOT NULL DEFAULT 0,
    prints INTEGER NOT NULL DEFAULT 0,
    shares INTEGER NOT NULL DEFAULT 0,
    handoffs INTEGER NOT NULL DEFAULT 0,
    batch_transliterations INTEGER NOT NULL DEFAULT 0,
    canvas_interactions INTEGER NOT NULL DEFAULT 0,
    template_uses INTEGER NOT NULL DEFAULT 0,
    background_image_uses INTEGER NOT NULL DEFAULT 0,
    summary_count INTEGER NOT NULL DEFAULT 0,
    length_0 INTEGER NOT NULL DEFAULT 0,
    length_1_20 INTEGER NOT NULL DEFAULT 0,
    length_21_50 INTEGER NOT NULL DEFAULT 0,
    length_51_100 INTEGER NOT NULL DEFAULT 0,
    length_101_250 INTEGER NOT NULL DEFAULT 0,
    length_251_500 INTEGER NOT NULL DEFAULT 0,
    length_501_1000 INTEGER NOT NULL DEFAULT 0,
    length_1001_2500 INTEGER NOT NULL DEFAULT 0,
    length_2500_plus INTEGER NOT NULL DEFAULT 0,
    active_0_10 INTEGER NOT NULL DEFAULT 0,
    active_11_30 INTEGER NOT NULL DEFAULT 0,
    active_31_60 INTEGER NOT NULL DEFAULT 0,
    active_61_180 INTEGER NOT NULL DEFAULT 0,
    active_181_600 INTEGER NOT NULL DEFAULT 0,
    active_600_plus INTEGER NOT NULL DEFAULT 0,
    input_roman INTEGER NOT NULL DEFAULT 0,
    input_direct INTEGER NOT NULL DEFAULT 0,
    input_unknown INTEGER NOT NULL DEFAULT 0,
    device_mobile INTEGER NOT NULL DEFAULT 0,
    device_tablet INTEGER NOT NULL DEFAULT 0,
    device_desktop INTEGER NOT NULL DEFAULT 0,
    latest_event_at TEXT,
    input_voice INTEGER NOT NULL DEFAULT 0,
    voice_exposed INTEGER NOT NULL DEFAULT 0,
    voice_selected INTEGER NOT NULL DEFAULT 0,
    voice_started INTEGER NOT NULL DEFAULT 0,
    voice_final INTEGER NOT NULL DEFAULT 0,
    voice_switch_continued INTEGER NOT NULL DEFAULT 0,
    voice_error_permission_denied INTEGER NOT NULL DEFAULT 0,
    voice_error_audio_capture INTEGER NOT NULL DEFAULT 0,
    voice_error_no_speech INTEGER NOT NULL DEFAULT 0,
    voice_error_network INTEGER NOT NULL DEFAULT 0,
    voice_error_language_unsupported INTEGER NOT NULL DEFAULT 0,
    voice_error_unknown INTEGER NOT NULL DEFAULT 0,
    community_views INTEGER NOT NULL DEFAULT 0,
    community_cta_clicks INTEGER NOT NULL DEFAULT 0,
    writer_viewed INTEGER NOT NULL DEFAULT 0,
    writer_focused INTEGER NOT NULL DEFAULT 0,
    writer_first_input INTEGER NOT NULL DEFAULT 0,
    writer_first_urdu_success INTEGER NOT NULL DEFAULT 0,
    writer_depth_20 INTEGER NOT NULL DEFAULT 0,
    writer_depth_100 INTEGER NOT NULL DEFAULT 0,
    writer_depth_500 INTEGER NOT NULL DEFAULT 0,
    writer_depth_1000 INTEGER NOT NULL DEFAULT 0,
    writer_outcome_first INTEGER NOT NULL DEFAULT 0,
    card_studio_export_step_reached INTEGER NOT NULL DEFAULT 0,
    card_studio_export_attempted INTEGER NOT NULL DEFAULT 0,
    card_studio_export_quick INTEGER NOT NULL DEFAULT 0,
    card_studio_export_advanced INTEGER NOT NULL DEFAULT 0,
    continuation_shown INTEGER NOT NULL DEFAULT 0,
    continuation_stored INTEGER NOT NULL DEFAULT 0,
    continuation_destination_ready INTEGER NOT NULL DEFAULT 0,
    continuation_payload_restored INTEGER NOT NULL DEFAULT 0,
    continuation_destination_meaningful_start INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (bucket_hour, device_class, tool)
);
